server:
  port: 9090

spring:
  application:
    name: gateway-service
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.4:8837,192.168.1.4:8848,192.168.1.4:8859
      config:
        server-addr: 192.168.1.4:8837,192.168.1.4:8848,192.168.1.4:8859
        file-extension: yaml
    gateway:
      discovery:
        locator:
          enabled: true # gateway 可以从 nacos发现服务，过 gateway调用 其他的微服务
      routes:
        - id: user_service_route #自己命名的，只要唯一即可
          uri: lb://user-service #强对应 user-service的 spring.application.name
          predicates:
            - Path=/** #to do
          filters:
            - StripPrefix=1 #使用过滤器